name: edium

services:
  doorman:
    build:
      context: ./doorman
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./doorman/.env
    ports:
      - "8081:80"
    depends_on:
      doorman_db:
        condition: service_healthy
      doorman-redis:
        condition: service_healthy

  doorman-db:
    image: postgres:18
    restart: unless-stopped
    env_file: ./doorman/.env
    ports:
      - "5433:5432"
    volumes:
      - doorman_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  doorman-redis:
    image: redis:8
    restart: unless-stopped
    command: ["redis-server","--requirepass","${REDIS_PASSWORD}","--appendonly","yes"]
    ports:
      - "6380:6379"
    volumes:
      - doorman_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20




volumes:
  doorman_db_data:
  doorman_redis_data:
