name: edium

services:
  doorman:
    build:
      context: ./doorman
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: ${DOORMAN_PG_USER}
      POSTGRES_PASSWORD: ${DOORMAN_PG_PWD}
      POSTGRES_DB: ${DOORMAN_PG_DB}
      REDIS_PASSWORD: ${DOORMAN_REDIS_PWD}
      JWT_RSA_PRIVATE_KEY: ${JWT_RSA_PRIVATE_KEY}
    ports:
      - "8081:80"
    depends_on:
      doorman-db:
        condition: service_healthy
      doorman-redis:
        condition: service_healthy
      doorman-flyway:
        condition: service_completed_successfully
      nats:
        condition: service_started

  doorman-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DOORMAN_PG_USER}
      POSTGRES_PASSWORD: ${DOORMAN_PG_PWD}
      POSTGRES_DB: ${DOORMAN_PG_DB}
    ports:
      - "5433:5432"
    volumes:
      - doorman_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  doorman-flyway:
    image: flyway/flyway:latest
    restart: no
    command: ["migrate"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://doorman-db:5432/${DOORMAN_PG_DB}
      - FLYWAY_USER=${DOORMAN_PG_USER}
      - FLYWAY_PASSWORD=${DOORMAN_PG_PWD}
      - FLYWAY_LOCATIONS=filesystem:/app/migrations
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
      - FLYWAY_BASELINE_ON_MIGRATE=true
    volumes:
      - ./doorman/migrations:/app/migrations
    depends_on:
      doorman-db:
        condition: service_healthy

  doorman-redis:
    image: redis:8
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${DOORMAN_REDIS_PWD}
    command: >
      sh -c 'exec redis-server --requirepass "$$REDIS_PASSWORD" --appendonly yes'
    ports:
      - "6380:6379"
    volumes:
      - doorman_redis_data:/data
    healthcheck:
      test: >
        sh -c 'redis-cli -a "$$REDIS_PASSWORD" ping | grep -q PONG'
      interval: 5s
      timeout: 3s
      retries: 20

  nats:
    image: nats:2.10
    restart: unless-stopped
    command:
      - "--js"
      - "--sd=/data"
      - "--name=nats"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data

volumes:
  nats_data:
  doorman_db_data:
  doorman_redis_data: